### ISSUE TITLE
simple deployment to demo.windingtree.com

### ISSUE THREAD

**Issue by kvbik** [windingtree/wt-demo-app#19]
prepare the build scripts. document the process.

and use plain gh-pages for now, we can point demo.windingtree.com there too

**Comment by JirkaChadima** [comment]
After #94, we have a way of building the final product. What we can't decide for now, is how and where will we host the app. The problem is as follows:

- Who builds the app? Developer or Travis? - I'm leaning towards Travis to get reproducible and environment-agnostic builds.
- Where is the app hosted? If Travis does the application build, we probably don't want it to commit back to our live repository on github. So we need to either host the page elsewhere or figure out how to totally restrict Travis's git permissions.

**Comment by kvbik** [comment]
i guess i prefer `now.js` because we can host there static page (this demo app) and later also node app (api).
